### ISSUE TITLE
About the official website of Responsive Material Design？

### ISSUE THREAD

**Issue by rowbone** [DimiMikadze/laravel-angular-cms#10]
Excuce me,What is the official website of Responsive Material Design？

**Comment by DimiMikadze** [comment]
what do you mean by  official website of Responsive Material Design ？

**Comment by rowbone** [comment]
I want to see the doc of Material

**Comment by DimiMikadze** [comment]
Just google "Google Material Design"

**Comment by DimiMikadze** [comment]
https://www.google.com/design/spec/material-design/introduction.html

**Comment by rowbone** [comment]
Thank you ,but i am in China
