### ISSUE TITLE
about the vendor

### ISSUE THREAD

**Issue by mjiong** [DimiMikadze/laravel-angular-cms#11]
I clone the zip from git,and the composer install.but composer fail.
I found that is the composer.lock old version?I copy another file and success to composer install.
But I failed   **[Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Illuminate\Routing\ControllerServiceProvider' not found**  .
How can I to fixed it?

**Comment by DimiMikadze** [comment]
after installing composer, did you go trough all readme instructions?

**Comment by mjiong** [comment]
@DimitriMikadze I am sorry I'm too busy this times.I did on all the readme instructions.
