### ISSUE TITLE
Where is Laravel rest API Feature ? 

### ISSUE THREAD

**Issue by rakesh-ideal** [DimiMikadze/laravel-angular-cms#12]
Hello,

Thank you for providing a great cms but I couldn't find the feature 'Laravel rest API' you listed under features.Can you please let me know where can I find it?

**Comment by DimiMikadze** [comment]
Hey,

thanks!

It's in app folder.

Models are in app folder, Gallery.php, Post.php ... and Controllers in app/http/Controllers/admin
