### ISSUE TITLE
Large set of data

### ISSUE THREAD

**Issue by sevmardi** [DimiMikadze/laravel-angular-cms#16]
I can't to figure out what kind of table lib you have implemented (or just haven't)? What if you want to search in large set of posts. Lets say 5000+

**Comment by DimiMikadze** [comment]
@sevmardi what you mean by table lib? there's no any specific search functionality for big data.

**Comment by sevmardi** [comment]
@DimitriMikadze  I just thought you were using libraries such as ngTable or smart table that's all. Thanks!
