### ISSUE TITLE
Categories 

### ISSUE THREAD

**Issue by raffaalves** [DimiMikadze/laravel-angular-cms#4]
Hi,

I like this project and i want contribute.

I'm begining create category sistem like wordpress, with category three.

It is interesting for the project?

**Comment by DimiMikadze** [comment]
Thanks! yes sure! :)

**Comment by dongzhuoyao** [comment]
I like the author's demo,which regulated my writing about angularjs,thx!

**Comment by DimiMikadze** [comment]
Thanks!
