### ISSUE TITLE
merge another admin template

### ISSUE THREAD

**Issue by odyright** [DimiMikadze/laravel-angular-cms#6]
is there a way to add admin Template like <a Href="http://themeforest.net/item/fuse-angularjs-material-design-admin-template/12931855?s_phrase=&s_rank=9">http://themeforest.net/item/fuse-angularjs-material-design-admin-template/12931855?s_phrase=&s_rank=9<a> to your cms?

**Comment by DimiMikadze** [comment]
No, you should change css by yourself if want another look.
