### ISSUE TITLE
Correct username and password combination. 

### ISSUE THREAD

**Issue by ps92** [DimiMikadze/laravel-angular-cms#7]
Are you sure you are proving the correct combination for the username and password? It does not seem to work. Or am I missing something?

**Comment by DimiMikadze** [comment]
i don't understand what you are asking for, you can't login ? did you seed the table with user info ?

**Comment by ps92** [comment]
Yes, I did seed it. 
![image](https://cloud.githubusercontent.com/assets/8271659/14887765/c6bf1e60-0d74-11e6-9fef-61dbb2f18fac.png)

But, I get error when I try to login in. 

I am diverted to dashboard, but I get redirected to login controller again.

**Comment by DimiMikadze** [comment]
Just follow the readme.md everything working.

you can check it on live demo:

http://128.199.34.169/admin/login

**Comment by callmesoul** [comment]
I'm the same way, the database has data, but is not logged on, log on with Administrator or demo make it. Trouble under the author for revision

**Comment by DimiMikadze** [comment]
This problem appears only when are u using locally or on live demo server http://128.199.34.169/admin/login ?

**Comment by ps92** [comment]
On localhost. 

Try yourself. On a new Homestead. I think you will find some problem or you might have missed something in readme.
