### ISSUE TITLE
Front end work

### ISSUE THREAD

**Issue by ArabicHTML** [DimiMikadze/laravel-angular-cms#8]
Hi Dimitri,
i was searching about frame working with laravel and angularJS , i find a lot but i feeled love with your laravel-angular-cms i think it will save for me half the way , i stil want make categories and subcategories and contact messages, and more , i'm looking into the  frame and i try to understand it,  if i will say i'm trying to follow the code but can you give me one example how i can output to the front end ...
i create new php controller for Post and return for me JSON good , but i don't want to go far away from the frame . so how i can get the json but with the framework help

**Comment by DimiMikadze** [comment]
Hey Amro, 

Thanks!

for example if you are going to create categories section, you should create model and controller for back end, for front end you should create views in /resources/views/admin and for angular:
create folder for categories in /resources/assets/js/admin/app/ create there controller, modules and routes files. ( categories.controller ... ) and add categories to app.modules /resources/assets/js/admin/app/app.modules.js

does it make sense ?

**Comment by ArabicHTML** [comment]
Hi Dimitri,
Don't worry ... after few days i begin to understand the frame , but you make it sure for me.
Thank you and i hope in the future showing you something nice with this frame

**Comment by DimiMikadze** [comment]
Thanks Amro, Looking forward!
